### ISSUE TITLE
compilation fails on cygwin

### ISSUE THREAD

**Issue by c-cube** [ocaml/ocamlbuild#104]
On 4.03, http://caml.inria.fr/mantis/view.php?id=7268 seems to affect ocamlbuild (which fails to compile) and therefore many packages that depend on it. I think it would be fixable in ocamlbuild by using `ocamlc` instead of `ocamlc.opt`?

**Comment by gasche** [comment]
The bug report says "fixed in flexdll", doesn't this mean that using a recent flexdll version in the OCaml cygwin setup should fix the issue?

**Comment by c-cube** [comment]
Might be so, but it doesn't seem flexdll has been released since the fix. I can try to see if a dev version can be installed.

**Comment by gasche** [comment]
@alainfrisch , could we get a flexdll release?

**Comment by alainfrisch** [comment]
I've just released flexdll 0.35.

**Comment by gasche** [comment]
@c-cube: could you confirm that it works using cygwin with the new flexdll release?

**Comment by c-cube** [comment]
thanks @alainfrisch ! I will wait until cygwin updates its package before I test, then I will report here.

**Comment by c-cube** [comment]
Still no update of flexdll on cygwin…

**Comment by whitequark** [comment]
Triage: this seems to have been fixed upstream.

**Comment by gasche** [comment]
Let's hope.
