### ISSUE TITLE
When compiling a program with two .cmo/.cmx, how to order them ?

### ISSUE THREAD

**Issue by gildor478** [ocaml/ocamlbuild#106]
(context: working on OASIS support for objects)

I have 3 files:
L.ml, content = 'let r = ref "a"'
O.ml, content = 'let () = L.r := "b"'
main.ml, content = 'let () = print_endline !L.r'

L.ml compiles to a library 'lib'
O.ml compile to an object 'obj'
main.ml depends on lib and obj and should compile to main.byte

What I want is that O.cmo is before main.cmo on command line so that L.r will get the value "b"/

What I get is that O.cmo is after main.cmo.

So far, I did that:

myocamlbuild.ml:
| After_rules ->
  dep ["link"; "ocaml"; "byte"; "use_obj_obj"]  ["O.cmo"] 

_tags:
"main.byte": use_lib
"main.byte": use_obj_obj

Here is the output for 'ocamlbuild -verbose 10 main.byte':

L.cmo already built
new dyndep for "ocaml: mllib & cmo\* -> cma (%=lib )"([ lib.cma ]): "L.cmo"
caml_transitive_closure ~caml_obj_ext:"cmo" ~pack_mode:true
  ~used_libraries:[  ] [ "L.cmo" ]
packages: {.  .}
dependency_map: {: "O.cmo" => {. L.cmo .}; "main.cmo" => {. L.cmo .};:}
used_files: {. L.cmo .}
open_packages: [  ]
lib_index: {::}
dependencies: {: "O.cmo" => {. L.cmo .}; "main.cmo" => {. L.cmo .};:}
caml_transitive_closure: [ "L.cmo" ] -> [ "L.cmo" ]
dyndeps: {. L.cmo .}
mid rule ocaml: mllib & cmo\* -> cma (%=lib ): cache hit
[cache hit] ocamlfind ocamlc -a L.cmo -o lib.cma
end rule ocaml: mllib & cmo\* -> cma (%=lib )
new dyndep for "ocaml: cmo\* -> byte (%=main )"([ main.byte ]): "lib.cma"
caml_transitive_closure ~caml_obj_ext:"cmo" ~pack_mode:false
  ~used_libraries:[ "lib.cma" ] [ "main.cmo"; "O.cmo" ]
packages: {.  .}
dependency_map:
  {:  
      "O.cmo" => {. L.cmo .};
      "lib.cma" => {. L.cmo .};
      "main.cmo" => {. L.cmo .};
  :}
used_files: {. L.cmo, O.cmo, main.cmo .}
open_packages: [  ]
lib_index: {: "L.cmo" => [ "lib.cma" ];:}
dependencies: {: "O.cmo" => {. lib.cma .}; "main.cmo" => {. lib.cma .};:}
caml_transitive_closure: [ "main.cmo"; "O.cmo" ] ->
  [ "O.cmo"; "main.cmo"; "lib.cma" ]
link: [ "lib.cma"; "main.cmo"; "O.cmo" ] -o main.byte
====> O.cmo
O.cmo already built
new dyndep for "ocaml: cmo\* -> byte (%=main )"([ main.byte ]): "O.cmo"
dyndeps: {. L.cmo, O.cmo, lib.cma .}
mid rule ocaml: cmo\* -> byte (%=main ): cache miss: a product is not in build dir (main.byte)
/home/gildor/.opam/4.03.0/bin/ocamlfind ocamlc -linkpkg lib.cma main.cmo O.cmo -o main.byte
resource_changed: main.byte
end rule ocaml: cmo\* -> byte (%=main )

Is there a way to define the order of O.cmo and main.cmo ?

**Comment by gasche** [comment]
As an OCaml programmer, the way I would solve this in a robust way is to add a spurious dependency from `main.ml` to `O.ml` (for example: `include (O : sig end)`). One solution in the build system exactly reflects that intuition: you can add a dependency from `main.cmo` to `O.cmo`, and ocamlbuild will then impose an ordering between at link-time. In your example you can do it by changing `"main.cmo": use_obj_obj` in your `_tags` file (instead of `"main.byte": ...`), and dropping the `"link"` tag on the `dep` call, or replacing it by `"compile"`.

**Comment by whitequark** [comment]
The question was answered, closing.
