### ISSUE TITLE
upgrade failed -  install ocamlbuild 0.9.3

### ISSUE THREAD

**Issue by gajaka** [ocaml/ocamlbuild#114]
Hi all,
I have tried to upgrade latest release by opam and got the error 
[ERROR] The compilation of ocamlbuild failed at "make -f configure.make all OCAMLBUILD_PREFIX=/Users/moobar/.opam/system OCAMLBUILD_BINDIR=/Users/moobar/.opam/system/bin
        OCAMLBUILD_LIBDIR=/Users/moobar/.opam/system/lib OCAML_NATIVE=true OCAML_NATIVE_TOOLS=true".
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
....
The following actions failed
  ∗  install ocamlbuild 0.9.3
Then I tried to revert using  
opam switch import "~/.opam/system/backup/state-20160921120245.export"
and it failed trying to install ocamlbuild 0.9.2
any advice or work-around I will highly appreciate.
Thanks in advance
Dragan

**Comment by gasche** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

This error seems unrelated to ocamlbuild. Is your programming environment correctly set up?

I see that you are using the `system` switch. If your package manager already provides an `ocamlbuild` package, you can install it this way (not using opam), and then run `opam install --fake ocamlbuild`, which will let opam know that ocamlbuild is available (outside its own control).

**Comment by gajaka** [comment]
I was able to update my system using opam update and then opam upgrade a few weeks ago . I did the same and it failed today. opam upgrade removed  Core and advised to use command above opam switch import "~/.opam/system/backup/state-20160921120245.export"
So something weird has been happening there.
Ok I am able to opam install --fake ocamlbuild but still cannot get back my Core and rest of the packages using opam switch import "~/.opam/system/backup/state-20160921120245.export"
Any idea what needs to be done ?

**Comment by gasche** [comment]
Do *not* run `opam install --fake ocamlbuild` if you don't have an ocamlbuild package on your system -- that is, if `ocamlbuild --help` actually does something in your system switch environment.

Other than that, I don't know, sorry. The `xcrun` error is obviously unrelated to anything OCaml-side, so I tihnk you changed something in your system in between (I guess something XCode-related?). You should google it and find the solution to make it go away.

**Comment by gajaka** [comment]
Ok I think I solved issue . On OSX I have installed xcode-select --install
I think it was not mandatory in the previous upgrade. Now i am able to revert to previous state using opam switch import "~/.opam/system/backup/state-20160921120245.export".

**Comment by gajaka** [comment]
opam upgrade works fine .. you can close issue as resolved as it was not up to OCaml.
