### ISSUE TITLE
ld: warning: directory not found for option '-Lcore/'

### ISSUE THREAD

**Issue by agarwal** [ocaml/ocamlbuild#12]
Not a serious issue, but wondering why this warning occurs.

```
$ touch myocamlbuild.ml

$ ocamlbuild -use-ocamlfind -plugin-tag "package(opam-lib)" -just-plugin
+ ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package opam-lib myocamlbuild.ml /Users/ashish/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ld: warning: directory not found for option '-Lcore/'
Finished, 1 target (0 cached) in 00:00:00.
```

**Comment by gasche** [comment]
I haven't managed to reproduce this yet, but I would suspect a wrong linking flag stored in the `opam-lib` compiled units (so "not ocamlbuild's fault") -- ocamlbuild does not have a `core/` subdirectory anywhere, but some versions of `opam-lib` do.

**Comment by gasche** [comment]
I tried to install the current package version of opam-lib. but I still cannot reproduce the issue. Could you maybe try to see if you can reproduce it compiling a simple executable unrelated to ocamlbuild, eg.

    cat "let () = print_newline ()" > foo.ml
    ocamlfind ocamlopt -package opam-lib -linkpkg foo.ml -o foo

?

**Comment by agarwal** [comment]
You're right. I'm closing this issue and have reported to ocaml/opam#2390.
