### ISSUE TITLE
MPR#6927: Patch from PR6733 does not work on OS X

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#149]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6927_
[original reporter: @whitequark ]

Amusingly, this is a case of doing more work than necessary and failing at it, because the linker invocation already includes the `-shared`/`-bundle` flag, added by the compiler driver (ocamlc/ocamlopt). On Linux the second instance of `-shared`, added by the `flag ["ocaml"; "link"; "output_shared"]` built-in rule, is ignored, but on OS X it conflicts with `-bundle`.

A patch is attached. I verified that it works on Linux and OS X. It probably also works on Windows, since now `output_so` includes no platform details not used in the compiler elsewhere, but I'm not sure. Flexlink might or might not be a problem for the 3rd party code that wishes to load the resulting DLLs.

---

The target is a bundle, but it is called `x.{byte,native}.so`. This is actually common practice, and there is no generally agreed upon file extension for bundles (although `.bundle` is often used), but ocamlbuild rules mention `.dylib`, which does not actually happen. A second patch is attached to alleviate that.

**Comment by whitequark** [comment]
The extension change was postponed indefinitely (https://github.com/ocaml/ocaml/pull/988#issuecomment-282307151), and ocamlbuild already does not pass -shared, so there's nothing more to be done here.
