### ISSUE TITLE
MPR#6096: Validate what is needed to fully support Windows

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#156]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6096_
[original reporter: @danmey ]

It would be nice to know what exactly is missing to support all the Windows ports (i.e, Cygwin, Mingw{32,64} and native). This is investigative tasks that suppose to generate issues in Mantis. [note: now in GitHub rather than Mantis]

**Comment by hhugo** [comment]
We now have CI for mingw and native
