### ISSUE TITLE
MPR#5752: missing dependencies at byte-code link with mlpack

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#163]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=5752_
[original reporter: @bobzhang]

This problem was reported twice in caml list. I came across such a problem once again.
https://groups.google.com/forum/?fromgroups=#!searchin/fa.caml/byte$20code$20mlpack/fa.caml/c5Q8q6ZdvDw/nIFGpdVuAaUJ [^]

Thanks

**Comment by whitequark** [comment]
This appears to be fixed, based on the mantis comments.
