### ISSUE TITLE
MPR#5201: Performance issue for ocamlbuild on Windows

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#171]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=5201_
[original reporter: Daniel Weil]

on Windows system, each command executed by ocambuild is encapsulated in a `bash -C` command which has a non negligeable overhead (~ 0.5s).
Unless the `Filename.quote` function is fixed, a simple improvement is to change a line in file `ocamlbuild/my_std.ml`,
In function `sys_command`, just replace the line
```
 let cmd = "bash -c "^Filename.quote cmd in
```
by 
```
  let cmd = "sh -c "^Filename.quote cmd in
```
ocamlbuild will go much faster on Windows.

---

Note: this PR was partially fixed, see the Mantis discussion.

**Comment by hhugo** [comment]
We're now using `dash` if available, or `sh`, with a fallback on bash.
