### ISSUE TITLE
ocamlbuild should not hardcode file extensions

### ISSUE THREAD

**Issue by whitequark** [ocaml/ocamlbuild#181]
... but rather fetch them from `ocamlc -config`, with the appropriate toolchain.

**Comment by whitequark** [comment]
@gasche We might want to address this in 0.11.

**Comment by whitequark** [comment]
Workaround: I think you can change that in myocamlbuild.ml, by mutating the Options.ext_dll and friends.

**Comment by gasche** [comment]
> @gasche We might want to address this in 0.11.

I would rather release what we have, and release more often if we have more. If you want to iterate faster on the cross-compilation work, there is absolutely no problem with having our next release in a month.

**Comment by whitequark** [comment]
> I would rather release what we have, and release more often if we have more.

Ok.

> in a month.

That's not "iterating fast" in my book...

**Comment by gasche** [comment]
If you are as willing to help with the releases than with review or triaging (thanks to you and @dbuenzli, by the way) so far, any release rate you like is fine.
