### ISSUE TITLE
MPR#6890: provide use_ocamlfind as a tag

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#185]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6890_
[original reporter: @bobzhang]

it would be nice that I can write
```
true: use_ocamlfind
```
so I don't need type ocamlbuild -use-ocamlfind everytime, thanks -- Hongbo

**Comment by bluddy** [comment]
Honestly, this should already be a default. Any package not using ocamlfind by default is not living in the modern Ocaml world. If something as small as this can't be fixed due to backwards compatibility, that's a real problem, and it suggests maybe forking is needed.

**Comment by dbuenzli** [comment]
> If something as small as this can't be fixed due to backwards compatibility, that's a real problem, and it suggests maybe forking is needed.

So you are going to be the brave soul who maintains `ocamlbuild` ? If not please keep these kind of comments for yourself, they achieve absolutely nothing except annoy current maintainters.

I think this can be closed in favour of https://github.com/ocaml/ocamlbuild/issues/48 which also has a link to a mantis issue where this was tried at some point (I don't remember exactly why it was reverted). @gasche's comment related to the semantics of `_tags` in MPR6890 is right in my opinion.

**Comment by whitequark** [comment]
Triage: is it even possible to meaningfully implement that? _tags is read much later after the command-line options are parsed, and the global state in Options is long recorded elsewhere by that point. In my understanding this (i.e. `true: use_ocamlfind`) request is too complex to implement for its value.

**Comment by gasche** [comment]
Let's close this in favor of simply changing the default, as discussed (now) in #214.
