### ISSUE TITLE
MPR#6145: camlidl support in ocamlbuild

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#189]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6145_
[original reporter: @edmcman]

It would be very nice if ocamlbuild officially supported camlidl targets.

**Comment by whitequark** [comment]
Triage: 
  * camlidl seems very obscure, should we maintain its parts in ocamlbuild tree?
  * in any case, we have ocamlbuild plugins, and some functionality, in my opinion, is better provided by a plugin.

**Comment by hcarty** [comment]
This makes sense as a plugin. I've written one before, a long while ago. If the need ever came up I could probably dig it up and share.

**Comment by gasche** [comment]
Let's close, then. @hcarty, I think that indeed sharing your plugin code (even if it is not perfect / has bitrotten a bit) could help people.

**Comment by hcarty** [comment]
https://github.com/hcarty/ocaml-hdf/blob/7cd8843fc07047ff008aa31d9444e8be656e1b30/myocamlbuild.ml#L48 if someone is interested at some point.
