### ISSUE TITLE
clarify argument to Echo

### ISSUE THREAD

**Issue by agarwal** [ocaml/ocamlbuild#19]
`Echo` prints a string list to a given file. Are the strings intended to be *lines*? If so, I'd expect a newline character to be added automatically, but it isn't. On the other hand, if they aren't meant to be lines, then I wonder why the argument is a `string list` instead of just `string`.

**Comment by gasche** [comment]
The `Echo` command was added in 95a2a3d3c2bd6a7c6d54a07e318ba93fda8f6f92 . It seems to have been the original intent to *not* add newlines after the list elements. I would guess that this was done as a lightweight way to avoid the quadratic-concatenation problem without having to resort to `Buffer`.

The documentation comment in `signatures.mli` mentions that no formatting is done:
```
    | Echo of string list * pathname
    (** Write the given strings (w/ any formatting) to the given file *)
```

any pull request to improve it (if only by removing the abbreviation which I personally find confusing) is of course warmly welcome.
