### ISSUE TITLE
MPR#6095: Interactive init of default project files

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#194]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6095_
[original reporter: @danmey ]

I'd like to do:
```
ocamlbuild -init
```
and then ocamlbuild will ask me few questions regarding the project (like use ocamlfind? parse META file? generate myocamlbuild.ml skeleton? default source directory? load packages for build rules? etc.)

maybe OASIS does that to some extent, but it would be nice to have it in core.

**Comment by whitequark** [comment]
Triage: I believe most people do not use ocamlbuild by itself but in conjunction with some system on top of it (topkg, oasis, etc). Therefore it is not the responsibility of ocamlbuild to do this.

**Comment by gasche** [comment]
Also sprach Zarathustra.
