### ISSUE TITLE
MPR#6094: Reading META files

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#195]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6094_
[original reporter: @danmey ]

As proposed by @dbuenzli, and already implemented in other build systems, we can easily parse META information and extract neeeded information, possibly about the dependencies.

---

[See also the long discussion in the Mantis PR]

**Comment by dbuenzli** [comment]
I wouldn't propose that anymore.
