### ISSUE TITLE
MPR#6067: Targets that spit out the files needed to install a .mllib

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#196]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=6067_
[original reporter: @dbuenzli]

The idea would be to introduce targets corresponding to mllib so that we know which files need to be installed to get a correctly working lib. 

Given the mllib: src/vg.mllib with:
```
Vg
Vgr_pdf
Vgr_svg
```
Invoking ocamlbuild src/vg.libfiles would create the following text file _build/src/vg.libfiles:
```
vgr_pdf.mli 
vgr_pdf.cmi
vgr_pdf.cmx 
vgr_svg.mli
vgr_svg.cmi
vgr_svg.cmx
vg.mli 
vg.cmi
vg.cmx
vg.cma
vg.a
vg.cmxa
vg.cmxs
```
Alternatively we could have two targets `src/vg.libbytefiles` and `src/vg.libnativefiles`, the disadvantage is that the intersection would not be empty. 

Alternatively we could have a target `src/vg.libbyte` and `src/vg.libnative` that actually builds all the needed targets and spits out/adds to the above `src/vg.libfile` according to what was invoked (but I guess that adding to a file must not be easy).

**Comment by dbuenzli** [comment]
As far as I'm concerned this can be closed. This is solved by [`topkg`](https://github.com/dbuenzli/topkg) for me. Note that to solve this properly `ocamlbuild`'s configuration capabilities would need to be greatly enhanced.

**Comment by whitequark** [comment]
topkg seems like a great solution here.
