### ISSUE TITLE
MPR#5956: Need option to override camlp4o command

### ISSUE THREAD

**Issue by damiendoligez** [ocaml/ocamlbuild#200]
_PR transferred from https://caml.inria.fr/mantis/view.php?id=5956_
[original reporter: @zhihan]

OCamlbuild allows one to specify the command to override `ocamlc`, `ocamlopt`, etc. We would like the same capability to override `camlp4o`. Note that a customized `camlp4o` command is allowed in `findlib.conf`

**Comment by whitequark** [comment]
Triage: I think, camlp4 being increasingly broken in 4.02+ (it still doesn't support most ppx nodes), we should not spend time improving camlp4-related functionality.

**Comment by gasche** [comment]
I think this falls under the status of "we are unlikely to implement this ourselves, but pull requests are welcome".

**Comment by dbuenzli** [comment]
I'd move on to close it.

**Comment by gasche** [comment]
@dbuenzli, I just gave you commit rights, in particular you should be able to triage yourself if you wish to.
