### ISSUE TITLE
We need a Changes file

### ISSUE THREAD

**Issue by gasche** [ocaml/ocamlbuild#22]
We need a `Changes` file to record changes in future versions and credit external contributors.

I like the format of the OCaml Changes files and I think we could simply reuse it -- to avoid decision fatigue. The ChangeLog file presently included at the project root is of historical interest only.

Ideally if we wanted to do things well we would include the OCaml `Changes` file, restricted to only the changes relevant to OCamlbuild, and at the end we would add the current `ChangeLog`, and we would prepend new changes at the top.

Any volunteer to bootstrap the project with, at least, one Change section for the future ocamlbuild release? (You can use NEXT_RELEASE as version numbre), following OCaml's format? @Armael ?

**Comment by Armael** [comment]
In the case where we would import the OCaml `Changes` file and merge it with the current `ChangeLog`, would we keep the `ChangeLog` syntax? It looks different from the syntax of `Changes`...

**Comment by Armael** [comment]
If we agree on some way of merging both, I could write a quick script that does that and PR the resulting `Changes` file.

**Comment by gasche** [comment]
Yes, keep the ChangeLog syntax, just add some header saying.

> The content below corresponds to the old Changelog, before ocamlbuild was included in the OCaml distribution. The version control history of those changes is unfortunately lost, but the log below is kept for historical purposes.

I don't think you need a script, just concatenating files by hand should work. Or are you thinking of scripting the filtering of Changes to keep the ocamlbuild-relevant stuff? For a first commit you could just keep the whole OCaml changes, from 4.02.3 to the first version to include ocamlbuild. (Filtering is delicate and I doubt the script can do it: there are OCamlbuild section to keep, but there may also be ocamlbuild-related stuff in the Bug fixes and Feature wishes sections, so I would guess that manual search and cut is more efficient here.)

**Comment by Armael** [comment]
Alright, I'll just concatenate `Changes` and `ChangeLog` then.

**Comment by Armael** [comment]
I was indeed thinking of filtering the `Changes` files, to keep only change messages that include `ocamlbuild`, and `ocamlbuild` sections. But indeed that may miss some patches.

**Comment by gasche** [comment]
"Le mieux est l'ennemi du bien". Feel free to try your script, we'll keep the result if it looks okay.

**Comment by Armael** [comment]
Humpf. I may try again another time, but let's say that for the moment my attempt at automatically filtering `Change`'s contents failed.

[PR 24](https://github.com/ocaml/ocamlbuild/pull/24) implements the simple solution.

**Comment by gasche** [comment]
Fixed in #24 .
