### ISSUE TITLE
Allow passing of -ccopt option to ocamlopt

### ISSUE THREAD

**Issue by NathanReb** [ocaml/ocamlbuild#236]
I'd like to be able to pass a `-ccopt` option to all `ocamlopt` invocations when building
my project but it seems the `ccopt` tag is only applied to `c` files and I can't find
either a tag or an ocamlbuild cli option allowing me to do this.

FTR I'm trying to profile a program using gprof and thus added a `true: profile` to my
`_tags` file. Problem is my gcc version makes it impossible, unless invoked with the
`-no-pie` option (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854704). Without
the `-no-pie` option, the binary execution produces a `gmon.out` file but gprof fails to
interpret it somehow.

Any suggestion?

Thanks!

**Comment by NathanReb** [comment]
cc @emillon

**Comment by gasche** [comment]
I am a bit surprised by the description of your problem as I don't understand how passing the `-ccopt` option to ocamlopt/ocamlc more often would make a difference for you. (To my knowledge the only case where `-ccopt` is used by ocamlopt/ocamlc, besides when they call the C compiler or linker, is that those flags are stored in `.cm{,x}a` libraries, but I don't think this is the difference you are relying on.) It may be that you are right and that the current implementation of `ccopt` needs to be changed to apply to both `"c"` and `"ocaml"` tags, but it may also be that you are somehow testing it incorrectly.

I think that trying the following experiments would be informative:

1. Do you have a specific test case where a known sequence of ocamlc/ocamlopt (without going through ocamlbuild) works as desired?

2. If you add a flag declaration for `profile` to add `-ccopt -no-pie` to your myocamlbuild.ml, does the project build work as you would like? (Example below)

3. If you add a more liberal `ccopt/cclib` implementation to your myocamlbuild.ml, does the project build work as you would like? (Example below)

```
let profile_no_pie () = (* to be called from the dispatcher *)
  flag ["ocaml"; "profile"; "native"] (S[A "-ccopt"; A "-no-pie"])
```

```
let extend_ccflags () = (* to be called from the dispatcher *)
  pflag ["ocaml"; "compile"] "cc" (fun param -> S [A "-cc"; A param]);
  pflag ["ocaml"; "link"] "cc" (fun param -> S [A "-cc"; A param]);
  pflag ["ocaml"; "compile"] "ccopt" (fun param -> S [A "-ccopt"; A param]);
  pflag ["ocaml"; "link"] "ccopt" (fun param -> S [A "-ccopt"; A param]);
  pflag ["ocaml"; "compile"] "cclib" (fun param -> S [A "-cclib"; A param]);
  pflag ["ocaml"; "link"] "cclib" (fun param -> S [A "-cclib"; A param]);
  ()
```

**Comment by emillon** [comment]
Hi,

Thanks for your quick answer.

For your point 1, here is a short example that demonstrates that `cc` (and its options) are used somewhere at link time:
```
% cat t.ml 
print_endline "test";;
% ocamlopt -p t.ml && rm -f gmon.out && ./a.out && gprof a.out
[...]
Index by function name

a.out: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), [...]
% ocamlopt -p -ccopt -no-pie t.ml && rm -f gmon.out && ./a.out && gprof a.out
[...]
Index by function name

  [18] alloc_generic_table    [37] caml_fl_init_merge     [51] caml_ml_out_channels_list
  [23] camlCamlinternalFormatBasics__entry [38] caml_fl_merge_block [52] caml_ml_output
  [24] camlPervasives__entry  [13] caml_flush_partial     [53] caml_ml_output_bytes
  [25] camlPervasives__flush_all_1193 [39] caml_fresh_oo_id [54] caml_ml_output_char
[...]
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), [...]
```

Thanks

**Comment by gasche** [comment]
Could you try solution 3, then, and confirm that it works? If it does, I'm fine with merging the change upstream as a bugfix.

( @rgrinberg: you contributed the `cc{lib,opt}(...)` implementation, so feel free to comment if you have feedback on this discussion. )

**Comment by NathanReb** [comment]
My current fix is to add the following to `myocamlbuild.ml`:

```
flag ["profile"; "link"] (S [A "-ccopt"; A "-no-pie"]);
```

I'll give your suggestions a go and come back to you!

**Comment by NathanReb** [comment]
Sorry for the late answer, solution 3 indeed work!
