### ISSUE TITLE
Improve target “ocamlbuild.install”

### ISSUE THREAD

**Issue by elfring** [ocaml/ocamlbuild#243]
I imagine that it can be a bit more efficient to call a few targets in a single command instead of [triggering further make processes in a recursive way](https://github.com/ocaml/ocamlbuild/blob/7115a9441ed11a736834305ea17a42ab1f251a4d/Makefile#L400 "Update candidate").
Would you like to integrate the following change?

```diff
-	$(MAKE) install-bin-opam
-	$(MAKE) install-lib-opam
-	$(MAKE) install-man-opam
-	$(MAKE) install-doc-opam
+	$(MAKE) install-bin-opam install-lib-opam install-man-opam install-doc-opam
```

Or: Will it become relevant to try these installation actions there in parallel?

**Comment by gasche** [comment]
Indeed, I am worried about what would happen in a parallel build, and risks of races to write to `.opam`.

We could change these rules to each write to a different file and then cat everything at the end. But frankly, given that their execution is instantaneous, I don't think it is worth the effort.

**Comment by gasche** [comment]
I think that this proposal would not improve the current state (it would make things more complex instead), so I'm closing it.

**Comment by elfring** [comment]
Can it be easier to combine four commands into one (by the suggested refactoring)?
