### ISSUE TITLE
Checking build commands for the usage of “Ocamlbuild_pack.Main”

### ISSUE THREAD

**Issue by elfring** [ocaml/ocamlbuild#246]
The source file “ocamlbuild.ml” is not explicitly mentioned in [the make script](https://github.com/ocaml/ocamlbuild/blob/7115a9441ed11a736834305ea17a42ab1f251a4d/Makefile#L92 "Update candidate") which is used so far.
By which compilation command can [the reference “Ocamlbuild_pack.Main”](https://github.com/ocaml/ocamlbuild/blob/6a7311b74a639f77868f8c2d25d74c46763bee24/src/ocamlbuild.ml#L17 "Calling the main function") be resolved then?

**Comment by gasche** [comment]
What do you mean by "not mentioned"? There is a `%.cmo: %.ml` rule and `ocamlbuild.byte` depends on `ocamlbuild.cmo`.

**Comment by elfring** [comment]
You are right that there are two pattern rules which could match to the source file “ocamlbuild.ml”.
Does the one which you mentioned provide the data (compilation parameters) so that the reference for the module “`Ocamlbuild_pack.Main`” can be resolved as desired?
