### ISSUE TITLE
Reconsider the movement of “ocamlbuild_pack$(EXT_OBJ)”

### ISSUE THREAD

**Issue by elfring** [ocaml/ocamlbuild#247]
The following commands are used in the recipe of [a make script](https://github.com/ocaml/ocamlbuild/blob/7115a9441ed11a736834305ea17a42ab1f251a4d/Makefile#L14 "Update candidate").

```make
…
	mv tmp/ocamlbuild_pack.cmx src/ocamlbuild_pack.cmx
	mv tmp/ocamlbuild_pack$(EXT_OBJ) src/ocamlbuild_pack$(EXT_OBJ)
```

I find that there are further risks to consider from the evaluation of the shown variable.
1. If the value would ever be “`.cmx`”, it would be tried to repeat the action which was performed in the line before. I would expect a failure then.
2. If the value would ever be “`.cmo`”, it would be tried to repeat an action which should be performed by a command in an other recipe. I would expect a failure then.
3. Can it happen anyhow to be empty?

The movement of this file might also indicate that a second file is generated by this make rule. I wonder that it is not specified within the corresponding targets list there.

**Comment by whitequark** [comment]
The `EXT_OBJ` variable can only ever contain `.o` or `.obj`.

The second file is not specified because every `.cmx` file is generated at the same time as a corresponding `$(EXT_OBJ)` file; no dependency tracking is necessary.

**Comment by elfring** [comment]
How much do you care for validation of input parameters (like the variable “`EXT_OBJ`”) from the software build configuration?


>…; no dependency tracking is necessary.

I find this software situation still unclear (and unsafe?).
Which OCaml compiler (byte or native version) do you find responsible for the generation of corresponding files types “cmi” and “obj”?

**Comment by gasche** [comment]
EXT_OBJ comes from the OCaml compiler configuration in `$(ocamlc -where)/Makefile.config`, it is not user-provided.

**Comment by whitequark** [comment]
> Which OCaml compiler (byte or native version) do you find responsible for the generation of corresponding files types “cmi” and “obj”?

"obj" is generated by ocamlopt. "cmi" is normally generated by an explicit ocamlc invocation on the "mli" file, except in case of packs, where both ocamlc and ocamlopt will generate a "cmi" file alongside a "cmo" or "cmx"+"obj" files depending on the compiler. As you astutely noticed, this creates a race condition, which I've previously hit while using `make -j`, which is why [this rule](https://github.com/ocaml/ocamlbuild/blob/7115a9441ed11a736834305ea17a42ab1f251a4d/Makefile#L160) serializes this part of the build.

**Comment by elfring** [comment]
* If you would like to offer an ordinary Autoconf script “configure”, I imagine a need for a closer look there.
* The available default values could eventually be adjusted by [other settings from a call of the program “make”](https://www.gnu.org/software/make/manual/html_node/Overriding.html "Overriding variables").
* I find it confusing at the moment to express safe rules for the mentioned combination of special files types.
  Can this serialisation approach be still incomplete?

**Comment by elfring** [comment]
>…; no dependency tracking is necessary.

I would like to add another view:
* It can be that the files “ocamlbuild_pack.cmi” and “ocamlbuild_pack.o[bj]” could be generated by both OCaml compiler variants besides the really needed file “ocamlbuild_pack.cm[ox]”.
  * I would find it clearer to express this fact also in the corresponding targets lists.
  * How do you think about to avoid unnecessary file movements generally?
* I guess that the mentioned “race condition” can be resolved if [the update suggestion “Using two temporary directories”](https://github.com/ocaml/ocamlbuild/issues/248 "Using two temporary directories for the generation of “ocamlbuild_pack.cm*”") will be integrated into the affected make script.
