### ISSUE TITLE
Using two temporary directories for the generation of “ocamlbuild_pack.cm*”

### ISSUE THREAD

**Issue by elfring** [ocaml/ocamlbuild#248]
The directory “tmp” is created by two recipes in [the make script](https://github.com/ocaml/ocamlbuild/blob/7115a9441ed11a736834305ea17a42ab1f251a4d/Makefile#L151 "Update candidate") which is used so far.
I imagine that this approach can become insufficient in the use case that a software build would be attempted in parallel.

How do you think about the possibility to work with two temporary directories for the generation of the desired file variant “ocamlbuild_pack.cm[ox]”?

**Comment by whitequark** [comment]
Sure, makes sense.
