### ISSUE TITLE
ocamlbuild should not add threads.{cma,cmxa} to the command line when tag thread is used

### ISSUE THREAD

**Issue by glondu** [ocaml/ocamlbuild#252]
Hello,

In Debian, ben fails to build with the ocaml 4.05.0+rc1 + ocamlfind 1.7.3 + ocamlbuild 0.11.0 toolchain, with the following error:

    steph@wencory:/tmp/ben-0.7.6$ ocamlbuild bin/ben.native
    Finished, 0 targets (0 cached) in 00:00:00.
    + ocamlfind ocamlopt -c -g -annot -thread -package dynlink -package unix -package threads -package pcre -package re.pcre -package netstring -package ocamlgraph -package tyxml -package fileutils -package postgresql -package parmap -package extlib -inline 1000 -I bin -I lib -I frontends -o bin/ben.cmx bin/ben.ml
    File "_none_", line 1:
    Warning 58: no cmx file was found in path for module Parmap, and its interface was not compiled with -opaque
    + ocamlfind ocamlopt -g -thread threads.cmxa -linkpkg -package dynlink -package unix -package threads -package pcre -package re.pcre -package netstring -package ocamlgraph -package tyxml -package fileutils -package postgresql -package parmap -package extlib -inline 1000 -I lib -I frontends -I bin lib/benl_core.cmx lib/benl_error.cmx lib/benl_base.cmx lib/benl_compression.cmx lib/benl_clflags.cmx lib/benl_parser.cmx lib/benl_lexer.cmx lib/benl_marshal.cmx lib/package.cmx lib/benl_modules.cmx lib/benl_parallel.cmx lib/benl_utils.cmx lib/query.cmx lib/benl_data.cmx lib/benl_frontend.cmx frontends/ben_download.cmx lib/benl_templates.cmx lib/dependencies.cmx frontends/ben_monitor.cmx frontends/ben_query.cmx frontends/ben_tracker.cmx bin/ben.cmx lib/libbenl.a -o bin/ben.native
    File "_none_", line 1:
    Error: Files /usr/lib/ocaml/threads/threads.cmxa
           and /usr/lib/ocaml/threads/threads.cmxa
           both define a module named Thread
    Command exited with code 2.
    Compilation unsuccessful after building 89 targets (84 cached) in 00:00:00.

In bytecode:

    steph@wencory:/tmp/ben-0.7.6$ ocamlbuild bin/ben.byte  
    Finished, 0 targets (0 cached) in 00:00:00.
    + ocamlfind ocamlc -g -thread threads.cma -linkpkg -package dynlink -package unix -package threads -package pcre -package re.pcre -package netstring -package ocamlgraph -package tyxml -package fileutils -package postgresql -package parmap -package extlib -I lib -dllib -lbenl -I lib -I frontends -I bin lib/benl_core.cmo lib/benl_error.cmo lib/benl_base.cmo lib/benl_compression.cmo lib/benl_clflags.cmo lib/benl_marshal.cmo lib/package.cmo lib/benl_modules.cmo lib/benl_parallel.cmo lib/benl_parser.cmo lib/benl_lexer.cmo lib/benl_utils.cmo lib/query.cmo lib/benl_data.cmo lib/benl_frontend.cmo frontends/ben_download.cmo lib/benl_templates.cmo lib/dependencies.cmo frontends/ben_monitor.cmo frontends/ben_query.cmo frontends/ben_tracker.cmo bin/ben.cmo lib/libbenl.a -o bin/ben.byte
    File "/usr/lib/ocaml/threads/threads.cma(Thread)", line 1:
    Warning 31: files /usr/lib/ocaml/threads/threads.cma(Thread) and /usr/lib/ocaml/threads/threads.cma(Thread) both define a module named Thread
    File "/usr/lib/ocaml/threads/threads.cma(Mutex)", line 1:
    Warning 31: files /usr/lib/ocaml/threads/threads.cma(Mutex) and /usr/lib/ocaml/threads/threads.cma(Mutex) both define a module named Mutex
    File "/usr/lib/ocaml/threads/threads.cma(Condition)", line 1:
    Warning 31: files /usr/lib/ocaml/threads/threads.cma(Condition) and /usr/lib/ocaml/threads/threads.cma(Condition) both define a module named Condition
    File "/usr/lib/ocaml/threads/threads.cma(Event)", line 1:
    Warning 31: files /usr/lib/ocaml/threads/threads.cma(Event) and /usr/lib/ocaml/threads/threads.cma(Event) both define a module named Event
    File "/usr/lib/ocaml/threads/threads.cma(ThreadUnix)", line 1:
    Warning 31: files /usr/lib/ocaml/threads/threads.cma(ThreadUnix) and /usr/lib/ocaml/threads/threads.cma(ThreadUnix) both define a module named ThreadUnix
    File "_none_", line 1:
    Error: Some fatal warnings were triggered (5 occurrences)
    Command exited with code 2.
    Compilation unsuccessful after building 78 targets (74 cached) in 00:00:00.

My analysis is that threads.{cma,cmxa} is ill-placed in ocamlfind invocation line, which seems to be ocamlbuild's fault. The problem seems to have been there for a long time, but is revealed now because the ocaml linker is more picky about duplicate modules.

In my opinion, adding threads.{cma,cmxa} (at the right location) is ocamlfind's job. Only it knows the threads->unix dependency and that threads.{cma,cmxa} must come after unix.{cma,cmxa}.

For the record, ben compiles with ocaml 4.02.3 + ocamlfind 1.6.2.

**Comment by gasche** [comment]
This is a problem with ben's `myocamlbuild.ml` code that implements its own version of `ocamlfind` support, and creates this conflict for itself. This is understandable, given that I suppose this code was written before ocamlbuild had reliable ocamlfind support.

What are the versions of ocaml that you wish ben to support? If they are all more recent than, say, 4.01, I think you can assume correct `-use-ocamlfind` behavior and try to simplify your home-grown `myocamlbuild.ml` and use `-use-ocamlfind` instead.

**Comment by glondu** [comment]
I "fixed" ben to use ocamlfind support of ocamlbuild. It works for ocaml 4.02.3 and 4.05.0, which is enough for me. This doesn't convince me that ocamlbuild is correct, but you can close this issue if you want.

**Comment by gasche** [comment]
ocamlbuild isn't very well-specified, but it does add `threads.cma` if someone uses the provided-by-default flag `thread`, and if you explicitly ask your `myocamlbuild.ml` to *also* use ocamlfind and add the `thread` package then there is not much ocamlbuild can do other than doing as you say.

Note that if you had used an other flag name than just the ocamlfind package name, for example `pkg_thread` that is standard in oasis I think (and previous pre-use-ocamlfind approaches to ocamlfind in ocamlbuild), the issue would have been avoided, as it carries no builtin semantics so it would just pass the ocamlfind option.

**Comment by gasche** [comment]
I'm curious now: who is the userbase for ben in Debian, is it widely used? What about the other packaging-related OCaml tools? My undestanding for example was that "comigrate", for example, never found adoption, despite being a sensible improvement over its predecessor, due to the technological barrier (people being more familiar with Python than OCaml). Are some of these tools finding wider usage within the Debian community?

**Comment by glondu** [comment]
Ben is used by the release team to [monitor transitions](https://release.debian.org/transitions/). This use makes it an important piece of the Debian infrastructure. I also use it myself (combined with lots of unreleased shell script snippets) to schedule test-rebuilds with e.g. a new version of OCaml.

You're right that OCaml is a technological barrier. However, there are some packaging-related tools written in OCaml that are used in Debian: (at least) dose3, ben and botch. I also routinely use the output of a script which computes [rebuilding instructions](https://people.debian.org/~nomeata/binNMUs-ocaml.txt) that is written in Haskell (another technological barrier). What about comigrate? I guess its lack of adoption is due to a lack of somebody to do the job of integrating it with the Debian infrastructure.

**Comment by mehdid** [comment]
fwiw, ben is also used is some other distributions, like:
- Ubuntu, https://people.canonical.com/~ubuntu-archive/transitions/
- Tanglu, http://qa.tanglu.org/transitions/

About comigrate, its lack of adoption is also explained by that fact that britney (the script than computes testing transitions) got a lot smarter (is now able to migrate ocaml and haskell stuff w/o any manual hint), a bit faster and easier to use. Also, comigrate is now lacking some features behind britney. An automatic hinter is not really needed anymore for britney and we've got less tricky transitions to debug manually. That made comigrate a bit less relevant than it used to be. So all in all, it still requires some work before promoting its use (if ever needed).
