### ISSUE TITLE
tests fail on powerpc because ld prints extra unexpected warnings

### ISSUE THREAD

**Issue by infinity0** [ocaml/ocamlbuild#254]
see e.g. https://buildd.debian.org/status/fetch.php?pkg=ocamlbuild&arch=powerpc&ver=0.11.0-1&stamp=1501347054&raw=0 :

~~~~
[m[0;31m[1m[FAILED][0m [1mModularPlugin2      [0;33mFailure with not matching message:
/usr/bin/ld: bss-plt forced due to /tmp/camlstartupb94de0.o
!=

.
[m[0;31m[1m[FAILED][0m [1mModularPlugin3      [0;33mFailure with not matching message:
Warning: tag "toto" does not expect a parameter, but is used with parameter "-g"
/usr/bin/ld: bss-plt forced due to /tmp/camlstartupc32af9.o
!=
Warning: tag "toto" does not expect a parameter, but is used with parameter "-g"
.
[m[0;32m[1m[PASSED][0m [1mPluginCompilation1  [0;36mcheck that the plugin is not compiled when -no-plugin is passed.
[m[0;32m[1m[PASSED][0m [1mPluginCompilation2  [0;36mcheck that the plugin is compiled when -just-plugin is passed.
[m[0;31m[1m[FAILED][0m [1mPluginCompilation3  [0;33mFailure with not matching message:
/usr/bin/ld: bss-plt forced due to /tmp/camlstartupf1498f.o
!=

.
~~~~

In fact the underlying issue is due to ocaml itself, but these extra warnings don't seem to affect ocaml's own testsuite which [passes despite the warnings](https://buildd.debian.org/status/fetch.php?pkg=ocaml&arch=powerpc&ver=4.05.0-6&stamp=1501323463&raw=0).

Googling the error message suggests this may be a potential security weakness as the alternative to bss-plt is called "secure-plt" [[1]](https://sourceware.org/bugzilla/show_bug.cgi?id=20554) [[2]](http://www.openwall.com/lists/musl/2014/10/16/17). I don't know if you care about it though since powerpc is not really a common platform.

I can file this over on the ocaml mantis BT tracker too if that would be more appropriate. In the meantime I will see if I can have ocamlbuild on Debian powerpc ignore these extra warnings in the same way that ocaml's own testsuite does.

**Comment by hhugo** [comment]
https://github.com/ocaml/ocaml/issues/8846
