### ISSUE TITLE
Tags "keep_docs" and "keep_locs" not honored when using ".mlpack"s

### ISSUE THREAD

**Issue by jacquev6** [ocaml/ocamlbuild#256]
Hello,

When tag `keep_docs` (resp. `keep_locs`) is used, `ocamlc -pack` is called without `-keep-docs` (resp. `-keep-locs`) option.

[This gist](https://gist.github.com/jacquev6/2c5d711d11243185205ec0a49e542a1d) is a minimal example showing the issue and proving that `ocamlc -pack -keep-docs` *does* keep the docs in the produced `.mli` file.

I might dive into ocamlbuild to provide a fix for that, but I wanted to report it first, in case it's a one-hour fix for someone who knows how.

Thanks!

**Comment by gasche** [comment]
Thanks for the report -- nice issue number!
