### ISSUE TITLE
Does not install properly on Windows (Appveyor)

### ISSUE THREAD

**Issue by Chris00** [ocaml/ocamlbuild#261]
Compiling [ocamlbuild-0.11.0](https://github.com/ocaml/ocamlbuild/archive/0.11.0.tar.gz) on AppVeyor with
```
    make configure
    make
```
 seem to work but `make install` [fails](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.183#L5358).

**Comment by gasche** [comment]
Indeed, it looks like there is a Unix-ism in the install script (assume `.o` instead of whatever variable holds the system-portable object file extension). Need to fix, and thanks for the report!

**Comment by gasche** [comment]
Note: I believe that almost no one is affected by this bug as people are using the `opam-install` and `findlib-install` targets.

**Comment by Chris00** [comment]
`findlib-install` [does not work any better](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.193#L5414).  I believe it is because the `install-bin` target is the one that fails.

**Comment by gasche** [comment]
I looked at it more tonight, and I don't see an obvious error (in particular I use `$(EXT_OBJ)` as I should). Are you sure that `make configure` is run correctly first, and does it work better with `make -f configure.make all`?  Can you access the content of `Makefile.config` after the configure step?

**Comment by Chris00** [comment]
[Listing the files](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.194#L5397) shows an `ocamlbuild.byte` in the toplevel directory but no `ocamlbuild.native`.

**Comment by Chris00** [comment]
Despite the fact that [`OCAML_NATIVE=true`](https://ci.appveyor.com/project/Chris00/ocaml-appveyor/build/1.0.194#L5196).

**Comment by gasche** [comment]
Ok, I found where the problem comes from: I was looking at `master` but the bug was fixed after 0.11 was released by a8d2e8ddf9891d2994bc47d2d3fd6a08db51443a. I have to make a new release and the problem will go away.

**Comment by gasche** [comment]
I'm in the process of releasing 0.12.0.

**Comment by gasche** [comment]
It's released now, so the issue should be fixed.
