### ISSUE TITLE
'inconsistent assumptions over implementation Unix' with Ocaml 4.04

### ISSUE THREAD

**Issue by gautierhattenberger** [ocaml/ocamlbuild#264]
Some distribution's packages are broken with Ocaml 4.04 with the following error:
```
+ ocamlfind ocamlopt unix.cmxa -I /usr/lib64/ocaml/ocamlbuild /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/lib64/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild.ml", line 1:
Error: Files /usr/lib64/ocaml/ocamlbuild/ocamlbuildlib.cmxa
       and /usr/lib64/ocaml/unix.cmxa
       make inconsistent assumptions over implementation Unix
Command exited with code 2.
```
This is reported on Fedora 26 (https://bugzilla.redhat.com/show_bug.cgi?id=1528513) and I can confirm it for Ubuntu 17.10 as well.

Is this a pure distributions issue or something wrong in the Ocaml buildsystem ?

**Comment by jpdeplaix** [comment]
This is most likely a distributions issue as the source code doesn't contain any compiled files.
My guess is that they updated their ```ocaml``` package but not the package that contains the ```ocamlbuild``` library.
