### ISSUE TITLE
How to generate only a statically linked clib?

### ISSUE THREAD

**Issue by hannesm** [ocaml/ocamlbuild#268]
I want to build only a statically linked c library, as done by passing `custom` or `failsafe` to `ocamlmklib`, but I fail to find a way how to pass such an option via `_tags` (and/or `myocamlbuild.ml`) to the build system.

repository in question is [mirage-xen](https://github.com/mirage/mirage-xen) on the `topkg` branch.  Any hints?

**Comment by hannesm** [comment]
In the latest commit on the branch mentioned above, the target is only `libmirage-xen_bindings.a`, I don't understand why ocamlbuild (or ocamlmklib) nevertheless tries to build the shared object.

**Comment by gasche** [comment]
I actually know little about static vs. dynamic linking in the non-OCaml world, so I am not sure how to test whether my experiments work or not. Please be patient :-) Also, I haven't had the time to build all of mirage-xen's dependecies, so I decided to experiment with a small repro case.

I have a file `lib.ml` and `lib.mli` with dummy content. The only rule in `ocamlbuild -documentation` that mentions `ocamlmklib` is the `.clib` one, so I created a `libfoo.clib` file with the following content:

```
lib.o
```

then `ocamlbuild -verbose 1 -tag custom libfoo.a` (or listing `true: custom` in _tags) runs the following commands:

```shell
ocamldep.opt -modules lib.ml > lib.ml.depends
ocamldep.opt -modules lib.mli > lib.mli.depends
ocamlc.opt -c -o lib.cmi lib.mli
ocamlopt.opt -c -o lib.cmx lib.ml
ocamlmklib.opt -o foo lib.o
```

If I understand correctly, the lack of a `-custom` flag passed to `ocamlmklib` in the final call is the issue for you. This should clearly be fixed upstream, but in the following I wrote the following `myocamlbuild.ml` script:

```ocaml
open Ocamlbuild_plugin

let _ = dispatch begin function
  | After_rules ->
    flag ["ocamlmklib"; "custom"] & A"-custom";
  | _ -> ()    
end
```

With this plugin file, I get the following behavior for the same command:

```shell
ocamldep.opt -modules lib.ml > lib.ml.depends
ocamldep.opt -modules lib.mli > lib.mli.depends
ocamlc.opt -c -o lib.cmi lib.mli
ocamlopt.opt -c -o lib.cmx lib.ml
ocamlmklib.opt -o foo -custom lib.o
```

(the `-custom` flag is indeed passed.)

Does that suffice to fix your issue? 

Note: if you wish to integrate the plugin within an OASIS project like `mirage-xen`, you should locate the 

```ocaml
Ocamlbuild_plugin.dispatch dispatch_default;;
```

line after the (*OASIS_STOP*) comment, and replace it with

```ocaml
...
(*OASIS_STOP*)
open Ocamlbuild_plugin

let _ = dispatch begin fun hook ->
  dispatch_default hook; (* this calls the OASIS stuff *)
  match hook with
  | After_rules ->
    flag ["ocamlmklib"; "custom"] & A"-custom";
  | _ -> ()    
end
```

**Comment by hannesm** [comment]
thanks @gasche, I used your snippets in https://github.com/mirage/mirage-xen/pull/1
