### ISSUE TITLE
Confused on install process - need help

### ISSUE THREAD

**Issue by stevenagy** [ocaml/ocamlbuild#281]
Hello,

I'm attempting to install ocaml/opam/ocamlbuild on an Ubuntu VM and am perplexed by the installation process. 

I installed opam via **sudo apt-get install**; any attempt to install ocamlbuild via **opam install ocamlbuild** fails. opam install anything fails. :(

Can someone please point me in the right direction? 

Thanks,
-Steve

**Comment by gasche** [comment]
If you want to install packages via opam, you should first install an opam "switch" to hold the packages. `opam switch install 4.07.0`. If you only need a production environment, not a development environment, and you don't plan to use opam, installing ocamlbuild through `apt-get` should also be fine (but it gives you less flexibility as to which version to install, etc.).

**Comment by stevenagy** [comment]
Afaik I only need production. I need to also install ocamlfind and opam package deriving, but attempting installation of either via the opam I got through sudo apt-get install fails. 

`opam install deriving
The following actions will be performed:
  ∗  install ocamlfind 1.8.0                  [required by deriving]
  ∗  install camlp4    4.04+system            [required by deriving]
  ∗  install ocamlmod  0.0.9                  [required by oasis]
  ∗  install ocamlify  0.0.1                  [required by oasis]
  ∗  install oasis     0.4.11                 [required by deriving]
  ∗  install deriving  0.8.1      
===== ∗  6 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[camlp4] Archive in cache
[deriving] Archive in cache
[oasis] Archive in cache
[ocamlfind] Archive in cache
[ocamlify] Archive in cache
[ocamlmod] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Processing  1/6: [camlp4: sh]rm: cannot remove '/home/osboxes/.opam/system/build/ocamlfind.1.8.0/site-lib-src/camlp4/META': Permission denied
rm: cannot remove '/home/osboxes/.opam/system/build/ocamlfind.1.8.0/site-lib-src/camlp4/META.in': Permission denied

#=== ERROR while installing ocamlfind.1.8.0 ===================================#
# opam-version    1.2.2
# os              linux
Cannot remove /home/osboxes/.opam/system/build/ocamlfind.1.8.0 (error 1).


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install deriving 0.8.1 
  ∗  install oasis    0.4.11
  ∗  install ocamlify 0.0.1 
  ∗  install ocamlmod 0.0.9 
The following actions failed
  ∗  install camlp4    4.04+system
  ∗  install ocamlfind 1.8.0      
No changes have been performed

=-=- camlp4.4.04+system troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext camlp4.4.04+system'
   may help you find the correct installation for your system.
`

I ran **opam depext opam depext camlp4.4.04+system** and am suggested to install **camlp4-extra**, but attempting so with opam produces **[ERROR] No package named camlp4-extra found**.

**Comment by gasche** [comment]
The problem comes from the fact that you are still in the "system" switch (a switch over the OCaml installed by your distribution), and some packages don't seem to work very well there. "opam switches" (over an OCaml compiler install by opam itself) work better.

To install a switch

```
opam switch install 4.07.0 # or another OCaml version
```

Once you have installed an opam compiler switch, you need to activate it in your shell

```
opam switch 4.07.0 # for example
eval $(opam config env)
```

You need to repeat `opam switch .. eval $(opam config env)` each time you want to have your OCaml environment available within a given shell/terminal. From there, you can run `opam install` etc.

**Comment by stevenagy** [comment]
I got it working. Thanks.
