### ISSUE TITLE
Opam package for version 0.13

### ISSUE THREAD

**Issue by Armael** [ocaml/ocamlbuild#291]
0.13 has been released since September, but there is currently no opam package for it.

**Comment by gasche** [comment]
See https://github.com/ocaml/opam-repository/pull/12586#issuecomment-419710003. There is a regression in 0.13 that I need to fix before a re-release.

**Comment by gasche** [comment]
@Armael note: if you felt motivated to help with the release, I think that could be very helpful. My plan for what is next is to revert the change that causes this breakage (it was fixing a bug in other builds, but that bug can be work-around in myocamlbuild.ml), and release 0.13.2 with that. I also need to figure a way to tell people not to use 0.13.{0,1}.

**Comment by anmonteiro** [comment]
@gasche Now that 4.08 is around the corner, and 0.12.0 doesn't build with 4.08, what's the status on releasing 0.13?

**Comment by gasche** [comment]
My plan is to revert the change that broke compatibility and release 0.14 after that.

**Comment by anmonteiro** [comment]
Thanks for the clarification.

**Comment by gasche** [comment]
0.14.0 has now been released on opam and is 4.08-compatible. Thanks for the pings!
