### ISSUE TITLE
New release for 4.08

### ISSUE THREAD

**Issue by copy** [ocaml/ocamlbuild#294]
0.12.0 is (rightly) restricted to <4.08, but compiling on the master branch already works on 4.08.0+beta1.

**Comment by gasche** [comment]
I just released 0.14.0, which should fix the issue. Could you confirm that it works as you expect?

**Comment by copy** [comment]
Yes, everything working as expected on 4.08.0+beta1 now. Cheers!

**Comment by aantron** [comment]
Confirmed, thank you!
