### ISSUE TITLE
build ocamlbuild fail

### ISSUE THREAD

**Issue by samikshro** [ocaml/ocamlbuild#301]
Hi! I am trying to install ocamlbuild on my computer (OS X High Sierra 10.13.6), but it keeps failing. I have attached the error message below. I installed opam using Homebrew, and my compiler version is 4.08.1.

Here are the commands I ran before I got this issue:
opam init --bare -a -y
opam switch create 4.08.1 ocaml-base-compiler.4.08.1
eval $(opam env)
opam install -y utop ounit qtest yojson lwt lwt_ppx menhir ansiterminal lambda-term merlin ocp-indent user-setup bisect_ppx-ocamlbuild

<img width="1280" alt="Screen Shot 2019-08-29 at 11 13 59 AM" src="https://user-images.githubusercontent.com/26678068/64047049-aa2b8a80-cb3b-11e9-9358-0a82ca70b004.png">

**Comment by gasche** [comment]
I have no idea what is going wrong here, and I cannot reproduce with 4.08.1+0.14.0 on my Linux machine.

Could you access a more complete error log? The display of the help message suggests that a command-line was passed to the compiler that it does not recognize, so maybe a version mismatch, but I don't see how that would happen.

Another thing that would help would be to see the content of the `Makefile.config` file generated during the build (to check that the paths refer to the right opam switch, with the right compiler version). Could you try this? The easiest way to do would be to get the sources (by cloning the git repository for example; building from `master` is fine) and use `opam install . --inplace-build`, which will build in place and thus create `Makefile.config` in the current directory.

**Comment by dbuenzli** [comment]
Just in case try again after an `opam udpate` that sometimes helps. 

To find the `Makefile.config` @gasche mention rather use `opam install --keep-build-dir` and simply go hunt for the `Makefile.config` in the build directory mentioned in `path` field of the error message. Also post the contents of the file mentioned in the `output-file` field of the error message somewhere.

**Comment by samikshro** [comment]
Just cloned the git repository and generated the Makefile.config. Here it is!
# This file was generated from configure.make

OCAML_PREFIX=
OCAML_BINDIR=/Users/samikshro/.opam/4.08.1/bin
OCAML_LIBDIR=/Users/samikshro/.opam/4.08.1/lib/ocaml
OCAML_MANDIR=/Users/samikshro/.opam/4.08.1/man

EXT_OBJ=.o
EXT_ASM=.s
EXT_LIB=.a
EXT_DLL=.so
EXE=

OCAML_NATIVE=true
OCAML_NATIVE_TOOLS=true
NATDYNLINK=true
SUPPORT_SHARED_LIBRARIES=true

PREFIX=/Users/samikshro/.opam/4.08.1
BINDIR=/Users/samikshro/.opam/4.08.1/bin
LIBDIR=/Users/samikshro/.opam/4.08.1/lib
MANDIR=/Users/samikshro/.opam/4.08.1/man

Also, @dbuenzli I tried installing again after opam update, but it didn't work.

Please let me know if you need more information!

**Comment by gasche** [comment]
There is nothing unexpected in this `Makefile.config` file, unfortunately. If you can do the build from the git master, could you get the full error log, and find the part that describes the command that fails and the beginning of the error message? (Your log above only had the end, without giving the command that failed).

**Comment by samikshro** [comment]
How do I access the full error log that has the command that failed? Is it the env-file or the output-file?

**Comment by gasche** [comment]
If you are in a build directory where the configuration was made according to the opam build recipe (the commands in `ocamlbuild.opam`, where `%{foo}%` refers to the result of `$(opam var foo)`), you should be able to just run `make all` there, and observe the same failure, with the full build trace in the console.

**Comment by samikshro** [comment]
We finally got it to build and install. But we still don't really know what was going wrong. The way that we fixed it was to go into the Makefile and replace the use of `$(LINKFLAGS)` in the `ocamlbuild.*` targets with `-I +unix -I src`, which is what `LINKFLAGS` originally is set to. This is what they contained instead: `-headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/lib`. We weren't able to figure out why `LINKFLAGS` was being set to this. 

tagging @sgpthomas

**Comment by dbuenzli** [comment]
Do you have `LINKFLAGS` defined in your environment ?

**Comment by sgpthomas** [comment]
@samikshro To test this out, run `echo $LINKFLAGS` in the terminal. You should also look at the `.env` files that I was looking at before. These are the ones generated by opam on a build fail. Unfortunately, I don't remember exactly where they are located. Something like `.opam/log`. Try and find the most recent one and let us know the results.

**Comment by dbuenzli** [comment]
Note that if you can still reproduce the failure path to these files are mentioned right at the beginning of the `opam` error message.

**Comment by samikshro** [comment]
`echo $LINKFLAGS` returns `-headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/lib`. 

Here is a `.env` file from `.opam/log`. I tried finding the most recent one, but all of them had the same `LINKFLAGS`.

`Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Idx1ZfxJGn/Render
CAML_LD_LIBRARY_PATH=/Users/samikshro/.opam/4.08.1/lib/stublibs:/Users/samikshro/.opam/4.08.1/lib/ocaml/stublibs:/Users/samikshro/.opam/4.08.1/lib/ocaml
CC=clang
CDPATH=
CFLAGS= -mmacosx-version-min=10.9 -fPIC
CMAKE_OSX_DEPLOYMENT_TARGET=10.9
CONDA_DEFAULT_ENV=base
CONDA_EXE=/Users/samikshro/anaconda3/bin/conda
CONDA_PREFIX=/Users/samikshro/anaconda3
CONDA_PROMPT_MODIFIER=(base)
CONDA_PYTHON_EXE=/Users/samikshro/anaconda3/bin/python
CONDA_SHLVL=1
CPPFLAGS= -I/include -I/include
CXX=clang++
CXXFLAGS= -mmacosx-version-min=10.9 -stdlib=libc++ -fPIC
F77=gfortran
F90=gfortran
F95=gfortran
FC=gfortran
HOME=/Users/samikshro
KIVY_HOME=/Users/samikshro/.kivy
LANG=en_US.UTF-8
LDFLAGS= -headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/lib -L/lib
LINKFLAGS= -headerpad_max_install_names -mmacosx-version-min=10.9 -lc++ -Wl,-rpath,/lib
LOGNAME=samikshro
MACOSX_DEPLOYMENT_TARGET=10.9
MACOSX_VERSION_MIN=10.9
MAKEFLAGS=
MAKELEVEL=
OCAML_NATIVE_TOOLS=false
OCAML_TOPLEVEL_PATH=/Users/samikshro/.opam/4.08.1/lib/toplevel
OLDPWD=/Users/samikshro
OPAMNOENVNOTICE=true
OPAM_PACKAGE_NAME=ocamlbuild
OPAM_PACKAGE_VERSION=0.14.0
OPAM_SWITCH_PREFIX=/Users/samikshro/.opam/4.08.1
PATH=/Users/samikshro/.opam/4.08.1/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/samikshro/anaconda3/bin:/Users/samikshro/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/usr/texbin:/usr/texbin
PWD=/Users/samikshro/ocamlbuild
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.p2DOBMbvjg/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=421
TERM_SESSION_ID=30671FF3-2FB0-49CD-8937-54262C2B3A1F
TMPDIR=/var/folders/q_/5kt7n9bx6j9bkztg1f60zj8m0000gn/T/
USER=samikshro
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/local/bin/opam
_CE_CONDA=
_CE_M=`

**Comment by sgpthomas** [comment]
yep that looks like it would cause this. I wonder what is setting this variable. I bet changing the name of the LINKFLAGS variable to something unique will fix this problem

**Comment by gasche** [comment]
The ocamlbuild Makefile uses something like:

```
OCAMLC    ?= ocamlc
OCAMLOPT  ?= ocamlopt
OCAMLDEP  ?= ocamldep
OCAMLLEX  ?= ocamllex

CP        ?= cp
COMPFLAGS ?= -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence
LINKFLAGS ?= -I +unix -I src
```

The use of `?=` makes those definitions rebindable by the user.

for OCAMLC, etc., CP it seems reasonable to let users rebind the definition.

For COMPFLAGS, LINKFLAGS, it may have been a mistake to let users redefine it -- as it is fragile when users have a dirty ambient environment. I don't know if we should consider changing this in the Makefile, at the risk of removing a capability that is useful sometimes.

(Another approach would be to give a definition of a local linkflags variable that appends the user-defined LINKFLAGS; but that would also break with the definition of LINKFLAGS reported here, which is designed for a C compiler rather than an OCaml compiler.)

**Comment by dbuenzli** [comment]
@gasche what's wrong with simply using `OCB_{LINK,COMP}FLAGS` ?

**Comment by gasche** [comment]
Nothing terribly wrong with that; this might in theory break people scripts, but I don't know if this availability is used in the wild. It's certainly not used by people installing ocamlbuild through OPAM, which accounts for the vast majority.
