### ISSUE TITLE
cmxs rules are mentioning .so without producing them

### ISSUE THREAD

**Issue by ivg** [ocaml/ocamlbuild#304]
All cmxs producing rules are mentioning a `.so`  as a product, though it is not able to produce it, at least on a Linux machine. The `link_shared` rule is creating a call to `ocamlopt` with the `-shared` option, which doesn't produce `.so` nor it is compatible with the `output-obj` option. 

This issue has a significant impact on (re)build times as it prevents the cache system from working properly. The cache system looks for the so file and retriggers linking for each library every time, even when nothing is changed.

**Comment by gasche** [comment]
Fixed by #305.
