### ISSUE TITLE
Cannot make from source or opam 

### ISSUE THREAD

**Issue by mjm2000** [ocaml/ocamlbuild#308]
when running make after cloning the repo, I get
```mkdir -p tmp
make: mkdir: Permission denied
make: *** [Makefile:155: src/ocamlbuild_pack.cmo] Error 127 
```
When I run "opam install ocamlbuild" I get the same. 
I'm on Manjaro Linux Kernal 5.4

**Comment by gasche** [comment]
This is fairly strange. The commend that appears to be failing is `mkdir -p tmp` (creating a `tmp` repository in the current directory, if it does not already exist). I don't see how that would fail with "permission denied". Do you indeed have the rights on the directory of the clone ? (I assume so.) Maybe add a `pwd` at the beginning of the `src/ocamlbuild_pack.cmo` rule to check that you are indeed in the expected (current) directory at the time this command is launched.
