### ISSUE TITLE
Publish glob as standalone library

### ISSUE THREAD

**Issue by hackwaly** [ocaml/ocamlbuild#309]
I want to use glob match. But I can't find such good glob library on opam compared to your implementation. 

Please publish it to opam.  Thanks for your awsome works!

**Comment by gasche** [comment]
Thanks for the request; I'm working on this.

(The Glob module was written by Berke Durak, one of the two original authors of ocamlbuild with Nicolas Pouillard, and he may not follow the issue discussions anymore, but I agree that his code is nice.)

**Comment by gasche** [comment]
I published this code as a standalone library: <https://gitlab.com/gasche/path_glob>.

I have not submitted the library to the opam-repository yet.

Would you be willing to give a try to the library and see if you can use it from your codebase first? There may be small things to change that I could fix before publishing the library.

**Comment by hackwaly** [comment]
I just tried it. Everything is fine except `opam pin` complains the `dune_project` hasn't a `name` field. I manunaly added it then it works well. 

```
# Error: The project name is not defined, please add a (name <name>) field to
# your dune-project file.
```

**Comment by gasche** [comment]
Thanks! I just added it. Tomorrow I will send it on opam-repository.

**Comment by gasche** [comment]
The library is now available as [path_glob](https://opam.ocaml.org/packages/path_glob/) on opam.
