### ISSUE TITLE
Can we have a unified opam file next version?

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/ocamlbuild#322]
It is cumbersome to have one `ocamlbuild.0.14.2/opam` version for Unix and another `ocamlbuild.0.14.2+win/opam` for Windows with availability flags to choose between both.

Among other things, we've lost the ability to pin ocamlbuild to a specific version.

I unified them in my own custom repository at https://github.com/diskuv/diskuv-opam-repository/tree/main/packages/ocamlbuild/ocamlbuild.0.14.2%2Bwin%2Bunix . Can we consider doing the same when it comes time to publish ocamlbuild.0.14.3? Thanks.

**Comment by kit-ty-kate** [comment]
For the record afaik none of the ocamlbuild maintainers were for the split. If I weren't undergoing a severe burnout at the time I would've never accepted this in the repository.

As far as I know we have not received any proper PR on this here repository for this yet and your contribution would be most welcome, thanks a lot!

see https://github.com/ocaml/opam-repository/pull/23832 for the original addition

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/26164
