### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by hhugo** [ocaml/ocamlbuild#350]
Testing in #348 didn't reveal any regression. 

Fix #322

@gasche, can I let you do this release ?

**Comment by gasche** [comment]
@hhugo to be honest, "doing releases" is something that I am likely to procrastinate over for a while. Are you sure you don't want to take care of it yourself? You did all the work in this release so it sort of makes sense as well.

**Comment by hhugo** [comment]
ok doing it now

**Comment by hhugo** [comment]
https://github.com/ocaml/opam-repository/pull/26164

**Comment by gasche** [comment]
Thanks!
