### ISSUE TITLE
lib.mllib with errors silently ignored for lib.ml{,i}

### ISSUE THREAD

**Issue by dsheets** [ocaml/ocamlbuild#42]
If you have both a `lib.mllib` file and `lib.ml{,i}` files and you attempt to make a `lib.cmxa` file when the `.mllib` file has module names which do not exist, the `.mllib` file will be ignored and the `.cmxa` file will only contain the `lib.ml{,i}` module and not the rest of the library. This silent failure is totally non-obvious and should not occur. Instead, I would expect `ocamlbuild` to halt with an error indicating that some of the targets in the `.mllib` could not be solved.

**Comment by gasche** [comment]
I believe this is the same issue as #11 . I of course agree this is a problem, but I won't have time to work on this in the short term. It's not an easy job, as it requires diving in the details of the target resolution machinery, but of course anyone willing to have a try is warmly welcome.

**Comment by whitequark** [comment]
I don't think this is the same as #11. In particular the failure in #11 is the error message is bad, but here the failure is that there's no error message.

**Comment by whitequark** [comment]
This is the same as #166 though; I am closing this issue because #166 has more context.
