### ISSUE TITLE
ppopt and ppxopt options

### ISSUE THREAD

**Issue by Drup** [ocaml/ocamlbuild#45]
It doesn't seem possible to add these ocamlfind options in the `_tag` file

**Comment by gasche** [comment]
Indeed; a pull request would be warmly welcome.

**Comment by whitequark** [comment]
Duplicate of #190, which has more context.

**Comment by argent-smith** [comment]
I've just encountered this issue: lwt docs say I can use ppxopt tag to specify -ppxopt lwt.ppx,-no-debug but I get "Warning: tag "ppxopt" does not expect a parameter, but is used with parameter "lwt.ppx,-no-debug" when compiling.

**Comment by gasche** [comment]
Thanks for the (reiterated) request, I proposed an implementation in https://github.com/ocaml/ocamlbuild/pull/265.
