### ISSUE TITLE
Ocamlbuild / Coq general issue

### ISSUE THREAD

**Issue by ejgallego** [ocaml/ocamlbuild#52]
This issue is to track progress of building Coq with ocamlbuild. Even if ocamlbuild is way slower than the current Coq's makefile system, I believe that this is an interesting goal for:
- Coq can benefit from easier integration with other packages and libraries, such as ppx rewriters.
- A Coq build is complex and allows for massive parallelism and would be a good benchmark for ocamlbuild itself.
## Current status:

My current efforts are at: https://github.com/ejgallego/coq/tree/ocamlbuild

Unfortunately, it doesn't work yet.
## Old issues:

Issues from the mantis tracker that are superseeded by this one are:
- http://caml.inria.fr/mantis/view.php?id=4935
- http://caml.inria.fr/mantis/view.php?id=4934

**Comment by ejgallego** [comment]
So as a good start, it would be great if an ocamlbuild expert could review what's currently there, it seems quite complex and I'm not sure how much of the pluging should be kept in a modern ocamlbuild setup.

**Comment by gasche** [comment]
I had a quick look; the stuff in `myocamlbuild.ml` seems generally to be specialized stuff, and I see nothing that would be obviously replaced by a "modern" ocamlbuild approach. (One candidate would be the `.cmxa -> .cxms` rule, but there is some special logic in it that I would guess is the reason why the default rule is not used.)

One thing that was not clear to me is the reason for the massive use of `include` in the [_tags file](https://github.com/ejgallego/coq/blob/4785e51/_tags). I would rather expect `traverse` tags instead (see [the documentation](https://github.com/gasche/manual-ocamlbuild/blob/master/manual.md#source-and-build-directories-module-paths-include-paths-) for the difference), and this might have a performance impact.

**Comment by ejgallego** [comment]
Thanks for the comments @gasche !

I'll will first try to build plugins with ocamlbuild, this should be quite useful.

**Comment by ejgallego** [comment]
We finally did some progress, now I can build coq toplevels with ocamlbuild, (in a bit of a hacky way). See:

- https://github.com/ejgallego/coq-serapi/blob/master/myocamlbuild.ml
- https://github.com/ejgallego/coq-serapi/blob/master/_tags

There's also a meta file that will hopefully be used soon:

- https://github.com/ejgallego/coq/commit/287700c0b1780e7777d5b332d3756fe11ed3a5b6

**Comment by letouzey** [comment]
Hi
I also devoted a few hours yesterday at repairing the build system of Coq via ocamlbuild.
The result of my effort is here:
https://github.com/letouzey/coq-wip/tree/ocamlbuild-partial-repair

Conclusion: both ocamlbuild and our specific tricks in our myocamlbuild.ml are way too fragile
for this alternative Coq build system to be maintainable. I devoted many hours to that in the past,
and won't continue. In particular, the debug of circularities reported by ocamlbuild is a pure nightmare (see my recent commits in the branch above). Moreover, these reported circularities aren't bothering our main make-based build system, apparently due to subtle differences in the way dependencies are computed by make vs. ocamlbuild.

I even intend to remove the ocamlbuild-specific files from the main git archive of Coq, since these files are relevent for only one person I know of (Emilio), in addition to being currently broken, hard to maintain and far from our Makefile in terms of features. Feel free to resuscitate these files in some other repository or branch, in case you want to continue working on it.
Best,
Pierre

**Comment by ejgallego** [comment]
That's interesting thanks Pierre! Yeah I guess it makes sense to remove ocamlbuild files from Coq.
 [Would you mind keeping the tree you pointed alive?]

I am taking a bit of different approach that is building the ide, toplevels, and plugins with ocamlbuild. This seems to work a bit better (indeed, the low level stuff is tricky), as once the cma files are in place things work.

**Comment by letouzey** [comment]
Sure, this ocamlbuild-partial-repair tree will stay accessible

**Comment by gasche** [comment]
Thanks for the feedback. We improved cycle printing in recent versions, so hopefully that will make life of future users better in that regard.

Note that having a dependency from `A.ml` to `B.ml` and from `A.mli` to `B.mli` is a rather dangerous thing to do. The OCaml compiler today is rather lax with this kind of quasi-circular dependencies, but this part of the language is not very well specified (the safer thing is to stay true to the notion of "compilation unit" that denotes the pair of .ml and .mli files), and such code may break in future OCaml versions. If you can split the part of `B.mli` that exports types to a  `B_types.mli` file on which both A and B depend, that is probably a safe move.

**Comment by ejgallego** [comment]
Not sure where to ask, asking here and giving a couple of updates on this issue:
- coqide, the Coq checker and custom coq toplevels, build fine with ocamlbuild. See my repositories in github for more info. Coq itself seems a bit trickier but IMO is almost there.
- I am seeing a strange thing, I'm sure I'm missing something. If you look at https://github.com/ejgallego/coq-serapi/tree/ocamlbuild_question , `_tags` doesn't work, but `_tags.old` does. The files differ as:
```
 # Sertop/Serlib general flags
-true: package(sexplib), package(ppx_sexp_conv)
 true: warn(+1..49-4-44), warn_error(+1..49-42), bin_annot, annot, safe_string
 
 # Serlib building options
 <serlib/*.{ml,mli}>: coq_lib, coq_clib, coq_kernel, coq_library, coq_intf, coq_engine, coq_pretyping, coq_interp
 <serlib/*.{ml,mli}>: coq_parsing, coq_stm, coq_proofs, coq_ltac
 <serlib/*.{ml,mli}>: package(ppx_import)
+<serlib/*>: package(sexplib), package(ppx_sexp_conv)

 # Sertop building options
 <serlib>: include
@@ -16,6 +16,7 @@
 <sertop/*.{ml,mli}>: coq_intf
 <sertop/*>: coq_config, coq_lib, coq_clib, coq_kernel, coq_vm, coq_library, coq_engine, coq_pretyping, coq_interp
 <sertop/*>: coq_parsing, coq_printing, coq_tactics, coq_stm, coq_proofs, coq_toplevel, coq_hparsing, coq_ltac
+<sertop/*>: package(sexplib), package(ppx_sexp_conv)
```
so I am not sure what I'm doing wrong. The error I get is:
```
+ ocamlfind ocamldep -package sexplib -package ppx_sexp_conv -package ppx_import -package str -package unix -package threads -modules serlib/ser_constr.ml > serlib/ser_constr.ml.depends
File "serlib/ser_constr.ml", line 39, characters 2-75:
unknown type
```
the coq packages are missing! Which doesn't make a lot of sense as the rule is unchanged.

**Comment by ejgallego** [comment]
A quick update:
- We got Coq 8.7 to a state where it is fairly easy to build toplevels or to reuse Coq as a library just using a simple tags file. Example: https://github.com/ejgallego/coq-serapi/blob/master/_tags CoqIDE also builds that way.
- I got to build Coq using ocamlbuild using a quite simple `myocamlbuild.ml` file, plus a 2-line patch to remove a spurious dependency on the Coq codebase. It needs a bit of extra work but it looks in a reasonable state IMHO, and replaces quite a few stuff including `coqmktop`.

**Comment by ejgallego** [comment]
A quick update; Coq builds fine with `ocamlbuild` without hacks; all that remains to be done is to cleanup the special rules that handle compilation of `.mlp/ml4` files.

In fact, there should not be any rules at all, and such files should be handled by `_tags`, but I think ocamlbuild won't recognize the dependency, right?

**Comment by gasche** [comment]
If you use a non-standard file extension you need a rule to tell ocamlbuild what to do with it.

**Comment by ejgallego** [comment]
Very silly question, `mlp/ml4` are not standard, right? [Lack of answer == I'll assume that indeed, they are not]

**Comment by ejgallego** [comment]
Update: now we are moving to Dune and abandoning the effort to use `ocamlbuild` with Coq, see https://github.com/coq/coq/pull/6857

There are two things were Dune works better for Coq: compositionality [so plugins and CoqIDE integrate much better] and speed. The speed delta for make/ocamlbuild was too large for my taste and I understand it was due to non-trivial design problems.

Nevertheless the Dune effort benefits great time from the work we've done modularizing the Coq codebase and sorting out some "interesting" dependencies chain that Coq was using. Thanks to all for all the help with `ocamlbuild` and Coq.

**Comment by gasche** [comment]
You're welcome! Happy to hear that Dune is working well for you.

(I hope that they get some form of `ppx_import` working for you to be also able to use it for Serapi and your other plugin-related venues.)
