### ISSUE TITLE
upgrading/downgrading ocamlfind breaks ocamlbuild?

### ISSUE THREAD

**Issue by edwintorok** [ocaml/ocamlbuild#59]
Thanks to ocamlbuild 0.9.1 a lot more packages build now, however upgrading/downgrading ocamlfind breaks the installed ocamlbuild (why upgrade/downgrade? because I used switch import and ended up with older ocamlfind).

Would it be possible to force reinstallation of `ocamlbuild` when `ocamlfind` is reinstalled by adding some dependency in ocamlbuild on ocamlfind?

It would seem that uninstallation of `ocamlfind` destroys everything that ocamlfind (had) META files for:`bigarray  bytes  camlp4.309  camlp4.310  compiler-libs  dbm  dynlink  graphics  labltk  num  num-top  ocamlbuild  stdlib  str  threads  unix`

```
$ opam reinstall ocamlbuild
[...]
$ find /home/edwin/.opam/4.03.0+beta1/ -name ocamlbuild.cmo
/home/edwin/.opam/4.03.0+beta1/lib/ocamlbuild/ocamlbuild.cmo
$ opam install ocamlfind.1.5.2
The following actions will be performed:
 - downgrade ocamlfind from 1.6.1 to 1.5.2
=== 1 to downgrade ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlfind.1.5.2] Downloading http://download.camlcity.org/download/findlib-1.5.2.tar.gz

=-=- Removing Packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Removing ocamlfind.1.6.1.
  ocamlfind remove bytes
  ./configure -bindir /home/edwin/.opam/4.03.0+beta1/bin -sitelib /home/edwin/.opam/4.03.0+beta1/lib -mandir /home/edwin/.opam/4.03.0+beta1/man -config /home/edwin/.opam/4.03.0+beta1/lib/findlib.conf
  make uninstall

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Copying ~/.opam/repo/beta/packages/ocamlfind/ocamlfind.1.5.2/files/ocamlfind.install to ~/.opam/4.03.0+beta1/build/ocamlfind.1.5.2/
Building ocamlfind.1.5.2:
  ./configure -bindir /home/edwin/.opam/4.03.0+beta1/bin -sitelib /home/edwin/.opam/4.03.0+beta1/lib -mandir /home/edwin/.opam/4.03.0+beta1/man -config /home/edwin/.opam/4.03.0+beta1/lib/findlib.conf
  make all
  make opt
  make install
Installing ocamlfind.1.5.2.
$ find /home/edwin/.opam/4.03.0+beta1/ -name ocamlbuild.cmo
$ opam install ocamlbuild

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlbuild] Fetching https://github.com/ocaml/ocamlbuild.git#0.9.1
[NOTE] Package ocamlbuild is already installed (current version is dev)
$ opam install base64
[...]
#=== ERROR while installing base64.2.0.0 ======================================#
# opam-version 1.2.0
# os           linux
# command      ocaml setup.ml -build
# path         /home/edwin/.opam/4.03.0+beta1/build/base64.2.0.0
# compiler     4.03.0+beta1
# exit-code    1
# env-file     /home/edwin/.opam/4.03.0+beta1/build/base64.2.0.0/base64-10581-c61e7b.env
# stdout-file  /home/edwin/.opam/4.03.0+beta1/build/base64.2.0.0/base64-10581-c61e7b.out
# stderr-file  /home/edwin/.opam/4.03.0+beta1/build/base64.2.0.0/base64-10581-c61e7b.err
### stdout ###
# ...[truncated]
# Turn ocaml profile flag on: .......................... false
# Compiler support generation of .cmxs.: ............... true
# OCamlbuild additional flags: ......................... 
# Create documentations: ............................... true
# Compile tests executable and library and run them: ... false
# pkg_bytes: ........................................... /home/edwin/.opam/4.03.0+beta1/lib/bytes
# ocamldoc: ............................................ /home/edwin/.opam/4.03.0+beta1/bin/ocamldoc
# 
# Warning: Won't be able to compile a native plugin
# Failure: Cannot find "ocamlbuild.cmo" in ocamlbuild -where directory.
### stderr ###
# ...[truncated]
# File "./setup.ml", line 1831, characters 16-35:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "setup.ml", line 5847, characters 11-28:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# File "setup.ml", line 5848, characters 11-30:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# E: Failure("Command ''/home/edwin/.opam/4.03.0+beta1/bin/ocamlbuild' lib/base64.cma lib/base64.cmxa lib/base64.a lib/base64.cmxs -tag debug' terminated with error code 2")
```

The workaround is to do `opam reinstall ocamlbuild`, which makes things work again (`ocamlbuild.cmo` is present).

**Comment by gasche** [comment]
Thanks for the report, I could reproduce.

ocamlfind seems to remove ocamlbuild's stuff when it is itself removed (it is a bug, not a packaging metadata issue). It comes from a mis-synchronization between the two tools , but I don't know who's making the wrong assumptions and what's the best way to fix this yet. Looking at it.

**Comment by edwintorok** [comment]
Is it due to the ocamlbuild compatibility library shipped by ocamlfind? it might thinks it owns ocamlbuild's META file even if the compat lib is not needed.

**Comment by gasche** [comment]
Yes, but I discussed this with Gerd when we split ocamlbuild off and at the time I understood that ocamlfind would do the right thing if it didn't find ocamlbuild's stuff inside `ocamlc -where`.

**Comment by gasche** [comment]
Ok, it's an ocamlfind bug, I will report.

**Comment by gasche** [comment]
I sent a patch to ocamlfind upstream. I will close the issue if/when an ocamlfind release is made with the fix. In the meantime, reinstalling ocamlbuild is indeed a perfectly reasonable workaround.

**Comment by gasche** [comment]
The patch is included in the latest findlib release, we should probably update the dependency -- but, ironically, putting the higher dependency means forcing people to reinstall findlib, which runs the old-findlib uninstall and thus fires the faulty code.

**Comment by whitequark** [comment]
Triage: should we add the dependency yet?

**Comment by gasche** [comment]
I think that could make sense: given that new OCaml versions will be released fairly soon, we can consider that many user will in fact upgrade ocamlbuild (and ocamlfind) at the same time, and that any extra recompilation would not be noticeable.

**Comment by gasche** [comment]
In fact, looking at this again, I see that in cedf5d8819436d7efb91c2838b5ee75fbb5123ea (part of 0.9.3) I added a `conflicts: [ "ocamlfind" {< "1.6.2"}]` clause, which I think has exactly the right semantics: ocamlbuild does not require ocamlfind to be present (after all, `-no-ocamlfind` exists), but if you install it along with ocamlfind it should be on a version without the bug (1.6.2 is the first release that included the bugfix). So I think that there should be nothing else to do here.  (Feel free to complain if I missed something).
