### ISSUE TITLE
Old ocamlbuild path still hardcoded inside ocaml_specific

### ISSUE THREAD

**Issue by fdopen** [ocaml/ocamlbuild#65]
I've just tried to build oasis with ocaml 4.03 and encountered this error here: https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1519&group_id=54&atid=291

So I've looked, where this dubious `-I +ocamlbuild ocamlbuildlib.cma` comes from. The culprit seems to be ocamlbuild itself: https://github.com/ocaml/ocamlbuild/blob/13feb3cafc1f4f664aca0a744f2f08e30bffd06a/src/ocaml_specific.ml#L750
I don't know, who is responsible to add all this flags to the build process in this context (ocamlbuild itself or oasis), but isn't `-I +ocamlbuild` usually wrong now?

**Comment by gasche** [comment]
Indeed, `+ocamlbuild` is wrong and I should have been more careful about this. We need to fix this.

Note that using `-use-ocamlfind -package ocamlbuild` should work fine. (I usually use this rather than `use_ocamlbuild` so I would not have noticed this defect myself.)

**Comment by dbuenzli** [comment]
Is this recent ? I was living happily in a 4.03 switch, I just did an opam upgrade and suddenly a lot of packages seem to be failing because of this.

**Comment by gasche** [comment]
The use of `+ocamlbuild` is not recent. Could it be that your previous version of the 4.03 switch still had in-distribution ocamlbuild, and that this is the first time you use the separately-distributed one?

**Comment by dbuenzli** [comment]
I always used the beta1 switch. But actually my error may be different: 
```
# ocamllex cppo_lexer.mll
# 368 states, 13139 transitions, table size 54764 bytes
# 3754 additional bytes used for bindings
# ocamlopt -o cppo -dtypes unix.cmxa str.cmxa cppo_version.ml cppo_types.ml cppo_parser.mli cppo_parser.ml cppo_lexer.ml cppo_command.ml cppo_eval.ml cppo_main.ml
# cd ocamlbuild_plugin && ocamlbuild -use-ocamlfind ocamlbuild_cppo.cma ocamlbuild_cppo.cmxa ocamlbuild_cppo.a ocamlbuild_cppo.cmxs
# ocamlfind ocamldep -package ocamlbuild -modules ocamlbuild_cppo.mli > ocamlbuild_cppo.mli.depends
# + ocamlfind ocamldep -package ocamlbuild -modules ocamlbuild_cppo.mli > ocamlbuild_cppo.mli.depends
# ocamlfind: Package `ocamlbuild' not found
# Command exited with code 2.
### stderr ###
# make: *** [ocamlbuild] Error 10
```

**Comment by dbuenzli** [comment]
It was something different. Somehow I reinstalled ocamlbuild and then everything went on smoothly.

**Comment by gasche** [comment]
This looks different, and it may be #59 if `ocamlfind` has been reinstalled but `ocamlbuild` hasn't -- try reinstalling `ocamlbuild`.
