### ISSUE TITLE
Choosing flambda optimizations via ocamlbuild

### ISSUE THREAD

**Issue by martin-neuhaeusser** [ocaml/ocamlbuild#67]
Is there any way of enabling the flambda optimization (e.g. -O3) in a build process with ocamlbuild?

**Comment by gasche** [comment]
We haven't added yet to the set of base flags yet. This should be rather easy, just adding flags to `ocaml_specific.ml` -- feel free to send a Pull Request implementing these.

Note that these flags will only work on OCaml compilers that have been configured (at compiler-build time) to use flambda.

**Comment by martin-neuhaeusser** [comment]
I am preparing a PR for the flambda optimization flags.
My suggestion for a name would be "optimize" with parameters classic, 2, or 3. Any objections?

@gasche: Can (and should?) ocamlbuild detect whether the underlying ocaml compiler includes flambda? Adding optimization flags in a non-flambda compiler results in a warning message...

**Comment by gasche** [comment]
The names are fine with me. Are you planning to also support the tuning options [documented in the manual](https://ocaml.janestreet.com/ocaml-core/flambda_manual/#sec450)?

I think we could just pass the flags to the underlying compiler, and let users handle warnings if they do the wrong thing.

**Comment by martin-neuhaeusser** [comment]
Which other tuning options should we support? I will try to incorporate them.
However, I am unsure which of them should be exposed in ocamlbuild?

Personally, I think the optimization levels (-O) and the inlining heuristic (-inline) are the most crucial ones. Please let me know if I should include, e.g. `-rounds`, `-unbox-closures`, or -remove-unused-arguments.

**Comment by Drup** [comment]
> Which other tuning options should we support?

All of them. There is no reason not to expose flags at the ocamlbuild level.

**Comment by martin-neuhaeusser** [comment]
I have a first draft for supporting the flambda options ready in #68.
