### ISSUE TITLE
[RFC] Migrate issues from the Mantis bugtracker

### ISSUE THREAD

**Issue by gasche** [ocaml/ocamlbuild#7]
I think that the only remaining blocker to complete the ocamlbuild split is the migration of existing issue reports from the [Mantis bugtracker of the compiler distribution](http://caml.inria.fr/mantis/). There are several ways to go at it and I would like to receive feedback and help if possible (my own time is very very limited until the end of the month).

We have several options, among which:
- "batch close": just decide to do nothing at all, and hope that important issues will resurface on the new issue tracker.
- "manual pick": manually import the issues that we feel are still relevant, and close the rest.
- "batch import": write a script importing issues automatically from a CVS export (it's easy to get those from mantis).

I don't like the "batch close" option; some free software projects have a policy of automatically closing inactive bug reports, and as a user I always find it mildly insulting to learn that the bug I reported five years ago died of old age instead rather than on the fixing-field.

I would be fine with either "manual pick" or "batch import". Here is [a link to the currently open Mantis issue in the OCamlbuild category](http://caml.inria.fr/mantis/search.php?project_id=1&category=OCamlbuild%20%28the%20tool%29&status_id[]=10&status_id[]=20&status_id[]=30&status_id[]=40&status_id[]=50&sticky_issues=on&sortby=last_updated&dir=DESC&per_page=200&hide_status_id=-2). It currently has 79 entries, meaning that either strategies would be manageable, especially if we start with a light pass of bug triaging (if you see an entry in there that should now be resolved or closed, just post a message saying this and I will do the change).

**Comment by ejgallego** [comment]
Hi @gasche ,

For the issues I care about (building Coq in paralell with ocamlbuild) "manual pick" seems the best. While we open a new issue here, I'd keep the old ones open until they are triaged. In particular these are the issues to port:

* http://caml.inria.fr/mantis/view.php?id=5754
* http://caml.inria.fr/mantis/view.php?id=4935
* http://caml.inria.fr/mantis/view.php?id=4934
* http://caml.inria.fr/mantis/view.php?id=4870 [maybe]

So they can be closed as we open a new issue, but we need to resurrect first Coq ocamlbuild scripts, which are broken in 8.5.

Waiting for manual triage may be sensible for the other issues.

**Comment by ejgallego** [comment]
By the way, the following issues look like they could be closed:

* http://caml.inria.fr/mantis/view.php?id=6402
* http://caml.inria.fr/mantis/view.php?id=5756

**Comment by ejgallego** [comment]
So I wonder how you would prefer to track the Coq issue:

* have two separated new issues: one for Coq build speed (which is pretty bad at the moment), and a more general issue for ocamlbuild's parallel buiding support.
* or to have a single general issue where both topics are addressed simultaneously.

**Comment by gasche** [comment]
Please do open issues, thanks! I'd rather two separate "mother issues", one for Coq build performance, and another for parallelization.

I don't know if you have already saw it but [this blog post](http://gallium.inria.fr/blog/ocamlbuild-parallelization/) summarizes what I know of ocamlbuild's parallelization issues and potential solutions.

**Comment by ejgallego** [comment]
Coq issues migrated to #52.

**Comment by ejgallego** [comment]
Umm, it seems I don't have the proper Mantis fu to close the Coq issues:
* http://caml.inria.fr/mantis/view.php?id=4935
* http://caml.inria.fr/mantis/view.php?id=4934

**Comment by whitequark** [comment]
This was done by @damiendoligez now, which I am grateful for.
