### ISSUE TITLE
ocamlbuild.0.9.1 : hygiene check does not exclude `_build` in Win32

### ISSUE THREAD

**Issue by camlspotter** [ocaml/ocamlbuild#71]
See https://github.com/ocaml/opam-repository/issues/6224 for details.

I think it is since `My_std.fiilename_concat` uses `/` in any OS.

**Comment by camlspotter** [comment]
Another glitch: `My_std.sys_command` gets `c:\cygwin\...\myocamlbuild.exe` and failed to execute using bash.  `\` must be replaced by `/` here...

The function is not different from ocamlbuild of ocaml.4.02.3.  Changes somewhere else caused this issue...

**Comment by gasche** [comment]
#70 should solve the first reported problem once the relevant parts are merged.

**Comment by camlspotter** [comment]
Hmm, I made a workaround of one line diff but yeah, we should have real fixes rather than workarounds.  Thanks.

**Comment by gasche** [comment]
I pushed a tentative first fix in master: b29023c86813a13dded7cece90d829bb9c8f5372 . Could you maybe try to check if it solves the problem on your Windows machine?
