### ISSUE TITLE
.odocl files: allow to specify files that are simply copied over

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocamlbuild#73]
An `.odocl` file should be a list of either a module name or a file. Files are simply copied over to the created doc dir. This allows to easily build doc with custom style, images, fonts etc.

I have been relying on ad-hoc scripts for years to do that simply copy.

**Comment by gasche** [comment]
What should the behavior be when they are in a subdirectory (`css/style.css`)? I assume we would only copy the file to the root of `foo.docdir` file? Would we also want to be able to specify a subdirectory path to move to?

**Comment by dbuenzli** [comment]
I think if this can be paths then you should also create paths in the doc dir.
