### ISSUE TITLE
Description of `.itarget`, `.otarget`

### ISSUE THREAD

**Issue by lindig** [ocaml/ocamlbuild#85]
The description of `.itarget`/`.otarget` in *Table 4. Basic targets* reads:

> Building `foo.itarget` requests the build of the targets listed (one per line) in the corresponding `foo.itarget`  file.

The implementation reads differently and thus I suspect a typo in the description above.

    rule "target files"
      ~dep:"%.itarget"
      ~stamp:"%.otarget"
      ~doc:"If foo.itarget contains a list of ocamlbuild targets, \
            asking ocamlbuild to produce foo.otarget will \
            build each of those targets in turn."

In any case, the purpose of these two target files escape me as I don't understand what `i` and `o` stand for in these rules. Maybe this could be addressed as well.

**Comment by gasche** [comment]
Thanks, I fixed the description and added a mnemonic for the file names.
