### ISSUE TITLE
Escaping problems on windows

### ISSUE THREAD

**Issue by ghost** [ocaml/ocamlbuild#89]
The Camlp4 build keeps on breaking on Windows due to escaping problems as reported on ocaml/camlp4#41. There was a workaround but it seems that [it doesn't work anymore](https://github.com/ocaml/camlp4/issues/41#issuecomment-222245642). How are we supposed to escape things with ocamlbuild on windows?

**Comment by gasche** [comment]
I would be happy to fix these issues (there should be no workaround needed on the user side), but the main issue I think is that I don't have reliable testing done on Windows. @diml , how are you doing your testing, do you have ssh-like access to a Windows machine? I'm thinking of investing my short-term maintenance budget into shaping a serious ocamlbuild test suite (including the current tests plus some complete builds of simple projects), and trying to get some kind of Windows CI for it. I would be happy to work with feedback from Windows users, and it would let me act on change proposals such as #70 that are currently stalled by lack of Windows feedback.

**Comment by diml** [comment]
I haven't been testing camlp4 on Windows so far. I have access to Windows machines at work so I can run some tests. For Windows CI AppVeyor seems to be popular. I want to look at it for various projects at some point

**Comment by msprotz** [comment]
I'm surprised because I didn't see any changes happen in ocamlbuild that would be related to quoting...

I can try building camlp4 with the old toolchain but that's ugly.

**Comment by msprotz** [comment]
Edit: you can't build camlp4 4.X with OCaml 4.Y (and X <> Y).
