### ISSUE TITLE
Local opam file

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/ocamlbuild#9]
Would be nice to be able to pin ocamlbuild to master.

**Comment by gasche** [comment]
Would you submit a pull request for this one? You can put me "Gabriel Scherer <gabriel.scherer@gmail.com>" as the maintainer (if several maintainers can be listed, you could add "whitequark <whitequar@whitequark.org>" and "François Bobot <francois@bobot.eu>").

**Comment by gasche** [comment]
Fixed by #41.
