### ISSUE TITLE
Passing OCAMLPATH environment variable to ocamlfind

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocamlbuild#90]
I got an inconvenience when I tried to enhance paths where ocamlfind searches for packages. I did this using `OCAMLPATH` environment variable and it works with ocamlfind but doesn't when ocamlbuild invokes ocamlfind. I didn't look into the code yet but probably we don't invoke ocamlfind directly in ocamlbuild and use a library for it.

````
➜  threads_test git:(compilable_demos) ✗ OCAMLPATH=../../lablqml/_build/bundle ocamlbuild -use-ocamlfind src/Controller.cmx
Finished, 0 targets (0 cached) in 00:00:00.
+ ocamlfind ocamlopt -c -g -thread -ppx 'ppx_qt -nocpp' -dsource -package compiler-libs.common -package str -package lablqml -w @6 -I src -o src/Controller.cmx src/Controller.ml
ocamlfind: Package `lablqml' not found
Command exited with code 2.
Compilation unsuccessful after building 3 targets (2 cached) in 00:00:00.
➜  threads_test git:(compilable_demos) ✗ OCAMLPATH=../../lablqml/_build/bundle ocamlfind list|grep lablqml             
84:lablqml             (version: 0.4)

````

Is there any easy way to fix this?

**Comment by gasche** [comment]
I think there is something wrong with your tests or some of your assumptions; `-use-ocamlfind` does call `ocamlfind` directly, as is shown in the log (the `+ ocamlfind ...` line in your output). I don't think that `ocamlbuild` changes the unix environment before calling ocamlfind either. Is this rather not a problem of specifying a relative path that becomes wrong when invoked from whithin the `_build` directory? I would try with `OCAMLPATH=$(pwd)/../../lablqml/_build/bundle` for example.

**Comment by Kakadu** [comment]
Oh, man, you are so good. I kind of tried full path recently but by some stupid reason it didn't work. Thanks a lot!
