### ISSUE TITLE
Wrong link for ocamlbuild manual

### ISSUE THREAD

**Issue by vrotaru** [ocaml/ocamlbuild#97]
```opam show ocamlbuild``` shows 

```sh                 
              doc: http://caml.inria.fr/pub/docs/manual-ocaml/ocamlbuild.html, 
                   https://github.com/gasche/manual-ocamlbuild/blob/master/manual.md

```

And none of those is correct.  The correct one seems to be this:  https://github.com/ocaml/ocamlbuild/blob/master/manual/manual.adoc

**Comment by gasche** [comment]
Indeed, good catch, thanks! I'll update the opam metadata.
