### ISSUE TITLE
Symlink are not cleaned if `-build-dir` is used. 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/ocamlbuild#98]
That is 
```
ocamlbuild -clean 
```
removes the symlink it created while 
```
ocamlbuild -build-dir _build -clean 
```
does not.

**Comment by dbuenzli** [comment]
In fact I now realize that symlinks are not created if you use `ocamlbuild -build-dir _build` (which is documented) so this is consistent.

**Comment by rleonid** [comment]
> that symlinks are not created if you use ocamlbuild -build-dir _build (which is documented)

Do you remember where that is documented? I just ran across this issue.

**Comment by rleonid** [comment]
I would also add that it might be nice to have a `-link` command line option in this case.
